'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ShieldCheck, SlidersHorizontal, TrendingUp, Users, Wallet, Repeat, Calendar, Layers, Activity, Sparkles, X } from 'lucide-react';
import { runModel, type ModelInputs } from '@/core/growth/model';
import { PRESET_SCENARIOS, BASELINE_INPUTS, RECOMMENDED_INPUTS } from '@/core/growth/scenarios';
import CometDial from './ui/CometDial';
import ProjectionSpace from './ProjectionSpace';
import './trading-experience.css';
const fields = [
 {key:'pricing.takerFeeBps',label:'Fee per trade',unit:'bps',min:1,max:20,step:.5,icon:Wallet},
 {key:'pricing.fxSpreadPct',label:'Currency conversion fee',unit:'%',min:.1,max:.5,step:.01,icon:Repeat},
 {key:'channel.paidBudgetUsd',label:'Paid ads budget',unit:'USD / month',min:0,max:20000,step:100,icon:TrendingUp},
 {key:'channel.crewEventsPerMonth',label:'Market Night events/month',unit:'events',min:0,max:8,step:1,icon:Calendar},
 {key:'channel.crewsPerEvent',label:'Crews per event',unit:'crews',min:0,max:200,step:1,icon:Users},
 {key:'channel.crewJoinRate',label:'Event → signup rate',unit:'%',min:0,max:100,step:1,scale:100,icon:ArrowUpRight},
 {key:'baseVolumePerActiveUsd',label:'Trading volume per person',unit:'USD / month',min:0,max:20000,step:100,icon:Activity},
 {key:'funnelRetention',label:'Traders who stay each month',unit:'%',min:0,max:100,step:1,scale:100,icon:Repeat},
 {key:'priceElasticity',label:'Fee sensitivity',unit:'×',min:0,max:2,step:.05,icon:SlidersHorizontal},
 {key:'trustElasticityDampening',label:'Trust protection effect',unit:'%',min:0,max:100,step:1,scale:100,icon:ShieldCheck},
];
function read(input:ModelInputs,key:string):number {const [a,b]=key.split('.');return b?(input[a as 'channel'|'pricing'] as unknown as Record<string,number>)[b]:input[a as keyof ModelInputs] as number;}
function Bull(){return <svg viewBox="0 0 160 140" fill="none" className="bull-mark" aria-label="MochaTrade bull emblem" role="img"><path d="M48 48C21 52 13 29 18 14C26 32 39 32 58 26M112 48C139 52 147 29 142 14C134 32 121 32 102 26" stroke="currentColor" strokeWidth="6" strokeLinejoin="round"/><path d="M49 31L80 22L111 31L119 62L103 82L99 113L80 126L61 113L57 82L41 62Z" stroke="currentColor" strokeWidth="3"/><path d="M49 59L68 67L62 75M111 59L92 67L98 75M65 103L80 96L95 103M80 24V86" stroke="currentColor" strokeWidth="3"/></svg>;}
function Backdrop(){return <div className="trading-backdrop" aria-hidden="true"><svg viewBox="0 0 1400 800" preserveAspectRatio="none">{[0,1,2].map(j=><polyline key={j} points={Array.from({length:35},(_,i)=>`${i*43},${540-j*90-Math.sin(i*1.7+j)*45-i*7}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1"/>)}{Array.from({length:40},(_,i)=><g key={i}><path d={`M${i*36} ${260+Math.sin(i)*60}v90`} stroke="currentColor"/><rect x={i*36-4} y={280+Math.sin(i)*60} width="8" height="40" fill="currentColor"/></g>)}</svg></div>;}
export default function TradingExperience({entry=false}:{entry?:boolean}){
 const router=useRouter();const reduced=useReducedMotion();const [login,setLogin]=useState(false);
 const [scenario,setScenario]=useState('recommended');const [input,setInput]=useState<ModelInputs>(()=>structuredClone(RECOMMENDED_INPUTS));
 const [selected,setSelected]=useState(0);const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [revenue,setRevenue]=useState(false);const [ladder,setLadder]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const baseline=useMemo(()=>runModel(BASELINE_INPUTS),[]),recommended=useMemo(()=>runModel(RECOMMENDED_INPUTS),[]),current=useMemo(()=>runModel(input),[input]);
 const f=fields[selected],value=read(input,f.key)*(f.scale??1);
 const update=(raw:number)=>{if(!Number.isFinite(raw))return;const n=Math.max(f.min,Math.min(f.max,Math.round((raw-f.min)/f.step)*f.step+f.min))/(f.scale??1);setInput(old=>{const next=structuredClone(old);const [a,b]=f.key.split('.');if(b)(next[a as 'channel'|'pricing'] as unknown as Record<string,number>)[b]=n;else(next as unknown as Record<string,number>)[a]=n;return next;});};
 const choose=(id:string)=>{setScenario(id);setInput(structuredClone(PRESET_SCENARIOS.find(s=>s.id===id)!.inputs));};
 const calculate=()=>{setBusy(true);timer.current=setTimeout(()=>{setBusy(false);setReady(true);},reduced?0:1100);};
 const series=[{name:'Baseline',color:'#a8bdd3',model:baseline},{name:'Recommended',color:'#ffb85f',model:recommended},{name:'Your scenario',color:'#65e4e6',model:current}];
 const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
 if(entry)return <main className="trading-entry"><Backdrop/><div className="entry-brand">MOCHATRADE <span>STRATEGY / TRUST / GROWTH</span></div><div className="entry-content"><Bull/><span className="studio-eyebrow">A CLEARER PERSPECTIVE</span><h1>Confidence.<br/><em>By design.</em></h1><p>Explore the mechanics of trust.<br/>Shape the next twelve months.</p><button className="silver-button" onClick={()=>setLogin(true)}>Log in to explore <ArrowUpRight size={18}/></button><small>Interactive strategy prototype</small></div>{login&&<div className="login-overlay" role="dialog" aria-modal="true" aria-label="Demo login" onKeyDown={e=>{if(e.key==='Escape')setLogin(false);if(e.key==='Tab'){const items=e.currentTarget.querySelectorAll<HTMLElement>('button,input');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><form className="login-card" onSubmit={e=>{e.preventDefault();router.push('/studio');}}><button type="button" className="login-close" aria-label="Close login" onClick={()=>setLogin(false)}><X/></button><Bull/><h2>Welcome to MochaTrade.</h2><p>Demo login. No password or account required.</p><label>Display name<input autoFocus placeholder="Your name" maxLength={50}/></label><button className="silver-button" type="submit">Enter workspace <ArrowUpRight size={17}/></button></form></div>}</main>;
 return <main className="strategy-studio"><Backdrop/><div className="studio-heading"><div><span className="studio-eyebrow">MOCHATRADE / STRATEGY STUDIO</span><h1>Build your perspective.</h1><p>Ten decisions. Twelve months. One connected model.</p></div><button className="silver-button ghost" aria-expanded={ladder} onClick={()=>setLadder(!ladder)}><Layers size={18}/>Trust ladder</button></div>
 {ladder&&<section className="trust-circuit"><div className="circuit-origin"><ShieldCheck/>THE TRUST LADDER</div>{input.trustLevers.map((lever,i)=><motion.div key={lever.id} className="circuit-branch" initial={reduced?false:{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:reduced?0:i*.18,duration:.6}}><span className="circuit-wire"><i/></span><Link href={lever.proofRoute}><span>0{i+1}</span><h3>{['Explainable Margin Health','Lost-ACK Recovery','Idempotent Deposits','Versioned Contract Rules + Receipts','Crew Pass Social Layer'][i]??lever.label}</h3><p>{lever.description}</p><small>Explore working demo ↗</small></Link></motion.div>)}</section>}
 <div className="studio-scenarios" role="group" aria-label="Choose scenario">{PRESET_SCENARIOS.map(s=><button key={s.id} aria-pressed={scenario===s.id} onClick={()=>choose(s.id)}>{s.name.replace(' ✓','')}<span>{s.id==='baseline'?'THE REFERENCE':s.id==='recommended'?'THE PROPOSAL':'THE CHALLENGE'}</span></button>)}</div>
 <section className="input-console"><div className="parameter-dock" role="group" aria-label="Model input controls">{fields.map((item,i)=>{const Icon=item.icon;return <button key={item.key} aria-pressed={selected===i} onClick={()=>setSelected(i)} title={item.label}><span><Icon size={21}/></span><small>{item.label}</small></button>;})}</div><div className="parameter-editor"><div><span className="studio-eyebrow">INPUT {String(selected+1).padStart(2,'0')} / 10</span><h2>{f.label}</h2><label className="number-control"><input aria-label={f.label} type="number" min={f.min} max={f.max} step={f.step} value={Number(value.toFixed(4))} onChange={e=>update(e.target.valueAsNumber)}/><span>{f.unit}</span></label><input aria-label={`${f.label} slider`} type="range" min={f.min} max={f.max} step={f.step} value={value} onChange={e=>update(+e.target.value)}/></div><CometDial key={f.key} value={value} min={f.min} max={f.max} step={f.step} unit={f.unit==='%'?'%':''} label={`${f.label} dial`} accent="#94d5f7" ink="#e2edf8" size={200} momentum={0.3} onChange={update} onChangeEnd={()=>{}}/></div><div className="console-footer"><button className="silver-button ghost" onClick={()=>choose(scenario)}>Reset scenario</button><button className="silver-button" onClick={calculate} disabled={busy}><Sparkles size={17}/>{ready?'Refresh projection':'Generate projection'}</button></div></section>
 <section className="comparison-strip" aria-label="Baseline versus recommended comparison">{series.slice(0,2).map(s=><article key={s.name}><span style={{color:s.color}}>{s.name} · 12 months</span><strong>{usd(s.model.totalRevenue12m)}</strong><small>Revenue · contribution {usd(s.model.totalContribution12m)}</small></article>)}</section>
 {busy&&<div className="calculation-orb" role="status"><div className="orb"><i/><i/><i/></div><p>Preparing your model view…</p><small>Illustrative scenario calculation</small></div>}
 {ready&&!busy&&<section className="results-panel"><div className="results-title"><div><span className="studio-eyebrow">12-MONTH FUNNEL</span><h2>Watch the strategy take shape.</h2></div><span className="live-chip">Updates with your inputs</span></div><ProjectionSpace series={series}/><button className="silver-button revenue-trigger" aria-expanded={revenue} onClick={()=>setRevenue(!revenue)}><TrendingUp size={20}/>12-month revenue projection</button>{revenue&&<ProjectionSpace series={series} revenue/>}{current.warnings.length>0&&<details className="data-details"><summary>Model notes ({current.warnings.length})</summary>{current.warnings.map(w=><p key={w}>{w}</p>)}</details>}</section>}
 <p className="studio-note">Prototype · All figures are model projections. Baseline and Recommended reference values remain unchanged; your editable scenario is shown separately. USD inputs; fee per trade is in basis points (1 bp = 0.01%).</p>
 </main>;
}
